version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
    name: frontend
    external: true
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}

services:

    ### PHP-FPM ##############################################
    php-fpm-sv:
      build:
        context: ./php-fpm
        args:
          - APP_ENV=${APP_ENV}
          - PROJECT_PHP_VERSION=${PHP_VERSION}
          - PUID=${PHP_FPM_PUID}
          - PGID=${PHP_FPM_PGID}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      environment:
        - DOCKER_TLS_VERIFY=1
        - DOCKER_TLS_CERTDIR=/certs
        - DOCKER_CERT_PATH=/certs/client
      networks:
        - backend
        - frontend

    ### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${APP_ADDRESS}`)"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsEncrypt"
        - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-compress.compress=true"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}-compress"
        - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
        - "traefik.docker.network=frontend"
        - "traefik.backend=nginx"
      depends_on:
        - php-fpm-sv
      networks:
        - frontend
        - backend

    ### MySQL ################################################
    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      command: ["--default-authentication-plugin=mysql_native_password", "--log_bin_trust_function_creators=1"]
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=UTC
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      networks:
        - backend

    ### phpMyAdmin ###########################################
    phpmyadmin:
      build: ./phpmyadmin
      depends_on:
        - mysql
      links:
        - mysql:mysql
      networks:
        - frontend
        - backend

    ### MySQL BACKUPS ########################################
    mysql-backup:
      build:
        context: ./mysql-backup
      environment:
        - DB_SERVER=mysql
        - DB_USER=${MYSQL_USER}
        - DB_PASS=${MYSQL_PASSWORD}
        - DB_NAMES=${MYSQL_DATABASE}
        - DB_DUMP_TARGET=/db
        - DB_DUMP_FREQ=${DB_DUMP_FREQ}
        - DB_DUMP_BEGIN=${DB_DUMP_BEGIN}
        - COMPRESSION=bzip2
        - NICE=true
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${APP_BACKUPS_FOLDER}/mysql:/db
        - ${DB_DUMP_SCRIPTS}/post-backup:/scripts.d/post-backup
      depends_on:
        - mysql
      links:
        - mysql:mysql
      networks:
        - frontend
        - backend
